//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorTOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        public int Id { get; set; }
        public string Street { get; set; }
        public string Home { get; set; }
        public string Domophone { get; set; }
        public int Floor { get; set; }
        public string Office { get; set; }
        public int IdClient { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
