//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorTOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Material
    {
        public int IdApplication { get; set; }
        public int IdMaterial { get; set; }
        public int Count { get; set; }
    
        public virtual ApplicationToReception ApplicationToReception { get; set; }
        public virtual Materials Materials { get; set; }
    }
}
