//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorTOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Demonstration = new HashSet<Demonstration>();
            this.Rent = new HashSet<Rent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronimic { get; set; }
        public string INN { get; set; }
        public string OGRN { get; set; }
        public string KPP { get; set; }
        public string Mail { get; set; }
        public string PathToCopyPassport { get; set; }
        public string PathToCopyContractOfDirector { get; set; }
        public string PathToCopyCertificateOfRegistrationOfaLegalEntity { get; set; }
        public string Street { get; set; }
        public string Home { get; set; }
        public string Domophone { get; set; }
        public string Floor { get; set; }
        public string Office { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> Del { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demonstration> Demonstration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rent { get; set; }
    }
}
