//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorTOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecommissionedMaterial
    {
        public int Id { get; set; }
        public int IdMaterial { get; set; }
        public int IdEmployee { get; set; }
        public string PathToDocument16 { get; set; }
        public int CountMat { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Materials Materials { get; set; }
    }
}
