//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorTOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demonstration
    {
        public int Id { get; set; }
        public Nullable<int> IdClient { get; set; }
        public int IdObjectRent { get; set; }
        public int IdEmployee { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronimic { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime DateOfDemonstration { get; set; }
        public System.TimeSpan TimeOfDemonstration { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ObjectRent ObjectRent { get; set; }
    }
}
