//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorTOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.Application_Material = new HashSet<Application_Material>();
            this.DecommissionedMat_Material = new HashSet<DecommissionedMat_Material>();
            this.SendMat_Material = new HashSet<SendMat_Material>();
            this.SupplyMaterial = new HashSet<SupplyMaterial>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int IdType { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<bool> Fragility { get; set; }
        public string Sizes { get; set; }
        public Nullable<int> CountMat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Material> Application_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecommissionedMat_Material> DecommissionedMat_Material { get; set; }
        public virtual TypeOfMaterial TypeOfMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SendMat_Material> SendMat_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyMaterial> SupplyMaterial { get; set; }
    }
}
