//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorTOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoOR
    {
        public int Id { get; set; }
        public int IdObject { get; set; }
        public string Path { get; set; }
    
        public virtual ObjectRent ObjectRent { get; set; }
    }
}
