//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorTOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int Id { get; set; }
        public int IdEmployee { get; set; }
        public int IdClient { get; set; }
        public int IdObjectRent { get; set; }
        public int IdTypeOfPayment { get; set; }
        public int IdDocument { get; set; }
        public string OwnerOfObjectRent { get; set; }
        public decimal Deposit { get; set; }
        public decimal Bet { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Document Document { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual FormOfPayment FormOfPayment { get; set; }
        public virtual ObjectRent ObjectRent { get; set; }
    }
}
