//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorTOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendMat_Material
    {
        public int Id { get; set; }
        public int IdMaterial { get; set; }
        public int IdObjectRent { get; set; }
        public int IdSendMaterial { get; set; }
        public int Count { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual ObjectRent ObjectRent { get; set; }
        public virtual SendMaterial SendMaterial { get; set; }
    }
}
